### ISSUE TITLE
No example code

### ISSUE THREAD

**Issue by algj** [dimdenGD/OWOP.js#7]
Please write an example how to use this, it WILL help others how to use it.

**Comment by dimdenGD** [comment]
same as normal ojs i guess with few changes

**Comment by algiuxass** [comment]
but I really don't know how to implement this ;-;

**Comment by dimdenGD** [comment]
`let bot = new OJS();
bot.on('open', () => {
bot.chat.send('test');
});`

**Comment by algj** [comment]
so you only have to run the browser.js and that's it?
also the other stuff isn't needed anymore which was on previous version?

**Comment by dimdenGD** [comment]
yes, just paste the code and done
